<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ARMSMemberDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR01-ARMSMember/ARMSMemberDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR01-ARMSMember/ARMSMemberDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ARMSMemberDB">
   <plt:partnerLinkType name="ARMSMemberDB_plt">
      <plt:role name="ARMSMemberDB_role">
         <plt:portType name="tns:ARMSMemberDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ARMSMemberDB" schemaLocation="xsd/ARMSMemberDB_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="MemberCollection_msg">
      <wsdl:part name="MemberCollection" element="top:MemberCollection"/>
   </wsdl:message>
   <wsdl:portType name="ARMSMemberDB_ptt">
      <wsdl:operation name="merge">
         <wsdl:input message="tns:MemberCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
